# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  enconding: unicode
  database: status_board_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  enconding: unicode
  database: status_board_test
  pool: 5
  username:
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: status_board_production
  pool: 5
  username:
  password:
